[can]
interface = socketcan
channel = vcan0
node = 62

# The Bitrate is not needed with the socketcan interface
#bitrate = 125000

# Logging configuration - See Python logging.config module documenation
[loggers]
keys=root

[handlers]
keys=stderr,file,syslog

[formatters]
keys=form1

[logger_root]
# messages with levels below the one given will not be logged
#level=DEBUG
level=INFO
#level=WARNING
#level=ERROR
#level=CRITICAL

handlers=stderr
#handlers=file
#handlers=syslog
propagate=1

[handler_stderr]
class=StreamHandler
formatter=form1
args=(sys.stderr,)

[handler_file]
class=FileHandler
formatter=form1
# Overwrites the log file each start
args=('cfutil.log', 'w')
# Appends to the log file
# args=('fixgw.log', 'a')

[handler_syslog]
class=handlers.SysLogHandler
formatter=form1
args=()

[formatter_form1]
format=%(levelname)s:%(asctime)s:%(name)s - %(message)s
datefmt=%Y%m%d-%H:%M:%S
class=logging.Formatter
