[can]
interface = socketcan
channel = can0
# The Bitrate is not needed with the socketcan interface
#bitrate = 125000
#auto_connect = yes


# List of default channels for some interfaces.  Should be a comma
# separated list with NO SPACES.
socketcan_channels = vcan0,vcan1,can0,can1,slcan0
kvaser_channels = 1,2,3,4,5,6,7,8,9
pcan_channels = 1,2,3,4,5

[canfix]
node = 62
device = 62
model = 1
version = 1

# Logging configuration - See Python logging.config module documenation
[loggers]
keys=root

[handlers]
keys=stderr,file,syslog

[formatters]
keys=form1

[logger_root]
# messages with levels below the one given will not be logged
#level=DEBUG
level=INFO
#level=WARNING
#level=ERROR
#level=CRITICAL

handlers=stderr
#handlers=file
#handlers=syslog
propagate=1

[handler_stderr]
class=StreamHandler
formatter=form1
args=(sys.stderr,)

[handler_file]
class=FileHandler
formatter=form1
# Overwrites the log file each start
args=('cfutil.log', 'w')
# Appends to the log file
# args=('fixgw.log', 'a')

[handler_syslog]
class=handlers.SysLogHandler
formatter=form1
args=()

[formatter_form1]
format=%(levelname)s:%(asctime)s:%(name)s - %(message)s
datefmt=%Y%m%d-%H:%M:%S
class=logging.Formatter
